apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: plant-id
type: Opaque
stringData:
   access-key-id: <aws-access-key>
   secret-access-key: <aws-secret-access-key>
#You can also create the secret using cli