apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plant-id-external-secret
  namespace: plant-id
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: plant-id-secrets
    creationPolicy: Owner
  data:
  - secretKey: GOOGLE_API_KEY
    remoteRef:
      key: plant-id
      property: GOOGLE_API_KEY